package com.sbs.pokerp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sbs.pokerp.model.BuyIn;
import com.sbs.pokerp.service.BuyInLocalServiceUtil;

/**
 * The extended model base implementation for the BuyIn service. Represents a row in the &quot;pokerp_BuyIn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BuyInImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see BuyInImpl
 * @see com.sbs.pokerp.model.BuyIn
 * @generated
 */
public abstract class BuyInBaseImpl extends BuyInModelImpl implements BuyIn {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a BuyIn model instance should use the {@link BuyIn} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BuyInLocalServiceUtil.addBuyIn(this);
        } else {
            BuyInLocalServiceUtil.updateBuyIn(this);
        }
    }
}
