package com.sbs.pokerp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sbs.pokerp.model.BuyIn;
import com.sbs.pokerp.model.BuyInModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BuyIn service. Represents a row in the &quot;pokerp_BuyIn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sbs.pokerp.model.BuyInModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BuyInImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see BuyInImpl
 * @see com.sbs.pokerp.model.BuyIn
 * @see com.sbs.pokerp.model.BuyInModel
 * @generated
 */
public class BuyInModelImpl extends BaseModelImpl<BuyIn> implements BuyInModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a BuyIn model instance should use the {@link com.sbs.pokerp.model.BuyIn} interface instead.
     */
    public static final String TABLE_NAME = "pokerp_BuyIn";
    public static final Object[][] TABLE_COLUMNS = {
            { "transactionId", Types.BIGINT },
            { "gameId", Types.BIGINT },
            { "playerId", Types.BIGINT },
            { "amount", Types.DOUBLE },
            { "credit", Types.BOOLEAN },
            { "createdBy", Types.VARCHAR },
            { "createdDate", Types.TIMESTAMP },
            { "updatedBy", Types.VARCHAR },
            { "updatedDate", Types.TIMESTAMP }
        };
    public static final String TABLE_SQL_CREATE = "create table pokerp_BuyIn (transactionId LONG not null primary key,gameId LONG,playerId LONG,amount DOUBLE,credit BOOLEAN,createdBy VARCHAR(75) null,createdDate DATE null,updatedBy VARCHAR(75) null,updatedDate DATE null)";
    public static final String TABLE_SQL_DROP = "drop table pokerp_BuyIn";
    public static final String ORDER_BY_JPQL = " ORDER BY buyIn.createdDate ASC";
    public static final String ORDER_BY_SQL = " ORDER BY pokerp_BuyIn.createdDate ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.sbs.pokerp.model.BuyIn"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.sbs.pokerp.model.BuyIn"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.sbs.pokerp.model.BuyIn"),
            true);
    public static long GAMEID_COLUMN_BITMASK = 1L;
    public static long PLAYERID_COLUMN_BITMASK = 2L;
    public static long CREATEDDATE_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.sbs.pokerp.model.BuyIn"));
    private static ClassLoader _classLoader = BuyIn.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { BuyIn.class };
    private long _transactionId;
    private long _gameId;
    private long _originalGameId;
    private boolean _setOriginalGameId;
    private long _playerId;
    private long _originalPlayerId;
    private boolean _setOriginalPlayerId;
    private double _amount;
    private boolean _credit;
    private String _createdBy;
    private Date _createdDate;
    private String _updatedBy;
    private Date _updatedDate;
    private long _columnBitmask;
    private BuyIn _escapedModel;

    public BuyInModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _transactionId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setTransactionId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _transactionId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return BuyIn.class;
    }

    @Override
    public String getModelClassName() {
        return BuyIn.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("transactionId", getTransactionId());
        attributes.put("gameId", getGameId());
        attributes.put("playerId", getPlayerId());
        attributes.put("amount", getAmount());
        attributes.put("credit", getCredit());
        attributes.put("createdBy", getCreatedBy());
        attributes.put("createdDate", getCreatedDate());
        attributes.put("updatedBy", getUpdatedBy());
        attributes.put("updatedDate", getUpdatedDate());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long transactionId = (Long) attributes.get("transactionId");

        if (transactionId != null) {
            setTransactionId(transactionId);
        }

        Long gameId = (Long) attributes.get("gameId");

        if (gameId != null) {
            setGameId(gameId);
        }

        Long playerId = (Long) attributes.get("playerId");

        if (playerId != null) {
            setPlayerId(playerId);
        }

        Double amount = (Double) attributes.get("amount");

        if (amount != null) {
            setAmount(amount);
        }

        Boolean credit = (Boolean) attributes.get("credit");

        if (credit != null) {
            setCredit(credit);
        }

        String createdBy = (String) attributes.get("createdBy");

        if (createdBy != null) {
            setCreatedBy(createdBy);
        }

        Date createdDate = (Date) attributes.get("createdDate");

        if (createdDate != null) {
            setCreatedDate(createdDate);
        }

        String updatedBy = (String) attributes.get("updatedBy");

        if (updatedBy != null) {
            setUpdatedBy(updatedBy);
        }

        Date updatedDate = (Date) attributes.get("updatedDate");

        if (updatedDate != null) {
            setUpdatedDate(updatedDate);
        }
    }

    @Override
    public long getTransactionId() {
        return _transactionId;
    }

    @Override
    public void setTransactionId(long transactionId) {
        _transactionId = transactionId;
    }

    @Override
    public long getGameId() {
        return _gameId;
    }

    @Override
    public void setGameId(long gameId) {
        _columnBitmask |= GAMEID_COLUMN_BITMASK;

        if (!_setOriginalGameId) {
            _setOriginalGameId = true;

            _originalGameId = _gameId;
        }

        _gameId = gameId;
    }

    public long getOriginalGameId() {
        return _originalGameId;
    }

    @Override
    public long getPlayerId() {
        return _playerId;
    }

    @Override
    public void setPlayerId(long playerId) {
        _columnBitmask |= PLAYERID_COLUMN_BITMASK;

        if (!_setOriginalPlayerId) {
            _setOriginalPlayerId = true;

            _originalPlayerId = _playerId;
        }

        _playerId = playerId;
    }

    public long getOriginalPlayerId() {
        return _originalPlayerId;
    }

    @Override
    public double getAmount() {
        return _amount;
    }

    @Override
    public void setAmount(double amount) {
        _amount = amount;
    }

    @Override
    public boolean getCredit() {
        return _credit;
    }

    @Override
    public boolean isCredit() {
        return _credit;
    }

    @Override
    public void setCredit(boolean credit) {
        _credit = credit;
    }

    @Override
    public String getCreatedBy() {
        if (_createdBy == null) {
            return StringPool.BLANK;
        } else {
            return _createdBy;
        }
    }

    @Override
    public void setCreatedBy(String createdBy) {
        _createdBy = createdBy;
    }

    @Override
    public Date getCreatedDate() {
        return _createdDate;
    }

    @Override
    public void setCreatedDate(Date createdDate) {
        _columnBitmask = -1L;

        _createdDate = createdDate;
    }

    @Override
    public String getUpdatedBy() {
        if (_updatedBy == null) {
            return StringPool.BLANK;
        } else {
            return _updatedBy;
        }
    }

    @Override
    public void setUpdatedBy(String updatedBy) {
        _updatedBy = updatedBy;
    }

    @Override
    public Date getUpdatedDate() {
        return _updatedDate;
    }

    @Override
    public void setUpdatedDate(Date updatedDate) {
        _updatedDate = updatedDate;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            BuyIn.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public BuyIn toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (BuyIn) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        BuyInImpl buyInImpl = new BuyInImpl();

        buyInImpl.setTransactionId(getTransactionId());
        buyInImpl.setGameId(getGameId());
        buyInImpl.setPlayerId(getPlayerId());
        buyInImpl.setAmount(getAmount());
        buyInImpl.setCredit(getCredit());
        buyInImpl.setCreatedBy(getCreatedBy());
        buyInImpl.setCreatedDate(getCreatedDate());
        buyInImpl.setUpdatedBy(getUpdatedBy());
        buyInImpl.setUpdatedDate(getUpdatedDate());

        buyInImpl.resetOriginalValues();

        return buyInImpl;
    }

    @Override
    public int compareTo(BuyIn buyIn) {
        int value = 0;

        value = DateUtil.compareTo(getCreatedDate(), buyIn.getCreatedDate());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof BuyIn)) {
            return false;
        }

        BuyIn buyIn = (BuyIn) obj;

        long primaryKey = buyIn.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        BuyInModelImpl buyInModelImpl = this;

        buyInModelImpl._originalGameId = buyInModelImpl._gameId;

        buyInModelImpl._setOriginalGameId = false;

        buyInModelImpl._originalPlayerId = buyInModelImpl._playerId;

        buyInModelImpl._setOriginalPlayerId = false;

        buyInModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<BuyIn> toCacheModel() {
        BuyInCacheModel buyInCacheModel = new BuyInCacheModel();

        buyInCacheModel.transactionId = getTransactionId();

        buyInCacheModel.gameId = getGameId();

        buyInCacheModel.playerId = getPlayerId();

        buyInCacheModel.amount = getAmount();

        buyInCacheModel.credit = getCredit();

        buyInCacheModel.createdBy = getCreatedBy();

        String createdBy = buyInCacheModel.createdBy;

        if ((createdBy != null) && (createdBy.length() == 0)) {
            buyInCacheModel.createdBy = null;
        }

        Date createdDate = getCreatedDate();

        if (createdDate != null) {
            buyInCacheModel.createdDate = createdDate.getTime();
        } else {
            buyInCacheModel.createdDate = Long.MIN_VALUE;
        }

        buyInCacheModel.updatedBy = getUpdatedBy();

        String updatedBy = buyInCacheModel.updatedBy;

        if ((updatedBy != null) && (updatedBy.length() == 0)) {
            buyInCacheModel.updatedBy = null;
        }

        Date updatedDate = getUpdatedDate();

        if (updatedDate != null) {
            buyInCacheModel.updatedDate = updatedDate.getTime();
        } else {
            buyInCacheModel.updatedDate = Long.MIN_VALUE;
        }

        return buyInCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{transactionId=");
        sb.append(getTransactionId());
        sb.append(", gameId=");
        sb.append(getGameId());
        sb.append(", playerId=");
        sb.append(getPlayerId());
        sb.append(", amount=");
        sb.append(getAmount());
        sb.append(", credit=");
        sb.append(getCredit());
        sb.append(", createdBy=");
        sb.append(getCreatedBy());
        sb.append(", createdDate=");
        sb.append(getCreatedDate());
        sb.append(", updatedBy=");
        sb.append(getUpdatedBy());
        sb.append(", updatedDate=");
        sb.append(getUpdatedDate());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.sbs.pokerp.model.BuyIn");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>transactionId</column-name><column-value><![CDATA[");
        sb.append(getTransactionId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>gameId</column-name><column-value><![CDATA[");
        sb.append(getGameId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>playerId</column-name><column-value><![CDATA[");
        sb.append(getPlayerId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>amount</column-name><column-value><![CDATA[");
        sb.append(getAmount());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>credit</column-name><column-value><![CDATA[");
        sb.append(getCredit());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createdBy</column-name><column-value><![CDATA[");
        sb.append(getCreatedBy());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createdDate</column-name><column-value><![CDATA[");
        sb.append(getCreatedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updatedBy</column-name><column-value><![CDATA[");
        sb.append(getUpdatedBy());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>updatedDate</column-name><column-value><![CDATA[");
        sb.append(getUpdatedDate());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
