package com.sbs.pokerp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sbs.pokerp.model.BuyOut;
import com.sbs.pokerp.service.BuyOutLocalServiceUtil;

/**
 * The extended model base implementation for the BuyOut service. Represents a row in the &quot;pokerp_BuyOut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BuyOutImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see BuyOutImpl
 * @see com.sbs.pokerp.model.BuyOut
 * @generated
 */
public abstract class BuyOutBaseImpl extends BuyOutModelImpl implements BuyOut {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a BuyOut model instance should use the {@link BuyOut} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BuyOutLocalServiceUtil.addBuyOut(this);
        } else {
            BuyOutLocalServiceUtil.updateBuyOut(this);
        }
    }
}
