package com.sbs.pokerp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sbs.pokerp.model.PokerTable;
import com.sbs.pokerp.service.PokerTableLocalServiceUtil;

/**
 * The extended model base implementation for the PokerTable service. Represents a row in the &quot;pokerp_PokerTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PokerTableImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see PokerTableImpl
 * @see com.sbs.pokerp.model.PokerTable
 * @generated
 */
public abstract class PokerTableBaseImpl extends PokerTableModelImpl
    implements PokerTable {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a PokerTable model instance should use the {@link PokerTable} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PokerTableLocalServiceUtil.addPokerTable(this);
        } else {
            PokerTableLocalServiceUtil.updatePokerTable(this);
        }
    }
}
