package com.sbs.pokerp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sbs.pokerp.model.PokerTablePlayer;
import com.sbs.pokerp.service.PokerTablePlayerLocalServiceUtil;

/**
 * The extended model base implementation for the PokerTablePlayer service. Represents a row in the &quot;pokerp_PokerTablePlayer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PokerTablePlayerImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see PokerTablePlayerImpl
 * @see com.sbs.pokerp.model.PokerTablePlayer
 * @generated
 */
public abstract class PokerTablePlayerBaseImpl extends PokerTablePlayerModelImpl
    implements PokerTablePlayer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a PokerTablePlayer model instance should use the {@link PokerTablePlayer} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PokerTablePlayerLocalServiceUtil.addPokerTablePlayer(this);
        } else {
            PokerTablePlayerLocalServiceUtil.updatePokerTablePlayer(this);
        }
    }
}
