package com.sbs.pokerp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BuyIn service. Represents a row in the &quot;pokerp_BuyIn&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbs.pokerp.model.impl.BuyInModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbs.pokerp.model.impl.BuyInImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see BuyIn
 * @see com.sbs.pokerp.model.impl.BuyInImpl
 * @see com.sbs.pokerp.model.impl.BuyInModelImpl
 * @generated
 */
public interface BuyInModel extends BaseModel<BuyIn> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a BuyIn model instance should use the {@link BuyIn} interface instead.
     */

    /**
     * Returns the primary key of this BuyIn.
     *
     * @return the primary key of this BuyIn
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this BuyIn.
     *
     * @param primaryKey the primary key of this BuyIn
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the transaction ID of this BuyIn.
     *
     * @return the transaction ID of this BuyIn
     */
    public long getTransactionId();

    /**
     * Sets the transaction ID of this BuyIn.
     *
     * @param transactionId the transaction ID of this BuyIn
     */
    public void setTransactionId(long transactionId);

    /**
     * Returns the game ID of this BuyIn.
     *
     * @return the game ID of this BuyIn
     */
    public long getGameId();

    /**
     * Sets the game ID of this BuyIn.
     *
     * @param gameId the game ID of this BuyIn
     */
    public void setGameId(long gameId);

    /**
     * Returns the player ID of this BuyIn.
     *
     * @return the player ID of this BuyIn
     */
    public long getPlayerId();

    /**
     * Sets the player ID of this BuyIn.
     *
     * @param playerId the player ID of this BuyIn
     */
    public void setPlayerId(long playerId);

    /**
     * Returns the amount of this BuyIn.
     *
     * @return the amount of this BuyIn
     */
    public double getAmount();

    /**
     * Sets the amount of this BuyIn.
     *
     * @param amount the amount of this BuyIn
     */
    public void setAmount(double amount);

    /**
     * Returns the credit of this BuyIn.
     *
     * @return the credit of this BuyIn
     */
    public boolean getCredit();

    /**
     * Returns <code>true</code> if this BuyIn is credit.
     *
     * @return <code>true</code> if this BuyIn is credit; <code>false</code> otherwise
     */
    public boolean isCredit();

    /**
     * Sets whether this BuyIn is credit.
     *
     * @param credit the credit of this BuyIn
     */
    public void setCredit(boolean credit);

    /**
     * Returns the created by of this BuyIn.
     *
     * @return the created by of this BuyIn
     */
    @AutoEscape
    public String getCreatedBy();

    /**
     * Sets the created by of this BuyIn.
     *
     * @param createdBy the created by of this BuyIn
     */
    public void setCreatedBy(String createdBy);

    /**
     * Returns the created date of this BuyIn.
     *
     * @return the created date of this BuyIn
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this BuyIn.
     *
     * @param createdDate the created date of this BuyIn
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the updated by of this BuyIn.
     *
     * @return the updated by of this BuyIn
     */
    @AutoEscape
    public String getUpdatedBy();

    /**
     * Sets the updated by of this BuyIn.
     *
     * @param updatedBy the updated by of this BuyIn
     */
    public void setUpdatedBy(String updatedBy);

    /**
     * Returns the updated date of this BuyIn.
     *
     * @return the updated date of this BuyIn
     */
    public Date getUpdatedDate();

    /**
     * Sets the updated date of this BuyIn.
     *
     * @param updatedDate the updated date of this BuyIn
     */
    public void setUpdatedDate(Date updatedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BuyIn buyIn);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BuyIn> toCacheModel();

    @Override
    public BuyIn toEscapedModel();

    @Override
    public BuyIn toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
