package com.sbs.pokerp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BuyOut service. Represents a row in the &quot;pokerp_BuyOut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbs.pokerp.model.impl.BuyOutModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbs.pokerp.model.impl.BuyOutImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see BuyOut
 * @see com.sbs.pokerp.model.impl.BuyOutImpl
 * @see com.sbs.pokerp.model.impl.BuyOutModelImpl
 * @generated
 */
public interface BuyOutModel extends BaseModel<BuyOut> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a BuyOut model instance should use the {@link BuyOut} interface instead.
     */

    /**
     * Returns the primary key of this BuyOut.
     *
     * @return the primary key of this BuyOut
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this BuyOut.
     *
     * @param primaryKey the primary key of this BuyOut
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the transaction ID of this BuyOut.
     *
     * @return the transaction ID of this BuyOut
     */
    public long getTransactionId();

    /**
     * Sets the transaction ID of this BuyOut.
     *
     * @param transactionId the transaction ID of this BuyOut
     */
    public void setTransactionId(long transactionId);

    /**
     * Returns the game ID of this BuyOut.
     *
     * @return the game ID of this BuyOut
     */
    public long getGameId();

    /**
     * Sets the game ID of this BuyOut.
     *
     * @param gameId the game ID of this BuyOut
     */
    public void setGameId(long gameId);

    /**
     * Returns the player ID of this BuyOut.
     *
     * @return the player ID of this BuyOut
     */
    public long getPlayerId();

    /**
     * Sets the player ID of this BuyOut.
     *
     * @param playerId the player ID of this BuyOut
     */
    public void setPlayerId(long playerId);

    /**
     * Returns the amount of this BuyOut.
     *
     * @return the amount of this BuyOut
     */
    public double getAmount();

    /**
     * Sets the amount of this BuyOut.
     *
     * @param amount the amount of this BuyOut
     */
    public void setAmount(double amount);

    /**
     * Returns the created by of this BuyOut.
     *
     * @return the created by of this BuyOut
     */
    @AutoEscape
    public String getCreatedBy();

    /**
     * Sets the created by of this BuyOut.
     *
     * @param createdBy the created by of this BuyOut
     */
    public void setCreatedBy(String createdBy);

    /**
     * Returns the created date of this BuyOut.
     *
     * @return the created date of this BuyOut
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this BuyOut.
     *
     * @param createdDate the created date of this BuyOut
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the updated by of this BuyOut.
     *
     * @return the updated by of this BuyOut
     */
    @AutoEscape
    public String getUpdatedBy();

    /**
     * Sets the updated by of this BuyOut.
     *
     * @param updatedBy the updated by of this BuyOut
     */
    public void setUpdatedBy(String updatedBy);

    /**
     * Returns the updated date of this BuyOut.
     *
     * @return the updated date of this BuyOut
     */
    public Date getUpdatedDate();

    /**
     * Sets the updated date of this BuyOut.
     *
     * @param updatedDate the updated date of this BuyOut
     */
    public void setUpdatedDate(Date updatedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(BuyOut buyOut);

    @Override
    public int hashCode();

    @Override
    public CacheModel<BuyOut> toCacheModel();

    @Override
    public BuyOut toEscapedModel();

    @Override
    public BuyOut toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
