package com.sbs.pokerp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.sbs.pokerp.service.persistence.PokerTablePlayerPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PokerTablePlayer service. Represents a row in the &quot;pokerp_PokerTablePlayer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sbs.pokerp.model.impl.PokerTablePlayerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sbs.pokerp.model.impl.PokerTablePlayerImpl}.
 * </p>
 *
 * @author jpnaidu
 * @see PokerTablePlayer
 * @see com.sbs.pokerp.model.impl.PokerTablePlayerImpl
 * @see com.sbs.pokerp.model.impl.PokerTablePlayerModelImpl
 * @generated
 */
public interface PokerTablePlayerModel extends BaseModel<PokerTablePlayer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a PokerTablePlayer model instance should use the {@link PokerTablePlayer} interface instead.
     */

    /**
     * Returns the primary key of this PokerTablePlayer.
     *
     * @return the primary key of this PokerTablePlayer
     */
    public PokerTablePlayerPK getPrimaryKey();

    /**
     * Sets the primary key of this PokerTablePlayer.
     *
     * @param primaryKey the primary key of this PokerTablePlayer
     */
    public void setPrimaryKey(PokerTablePlayerPK primaryKey);

    /**
     * Returns the game ID of this PokerTablePlayer.
     *
     * @return the game ID of this PokerTablePlayer
     */
    public long getGameId();

    /**
     * Sets the game ID of this PokerTablePlayer.
     *
     * @param gameId the game ID of this PokerTablePlayer
     */
    public void setGameId(long gameId);

    /**
     * Returns the player ID of this PokerTablePlayer.
     *
     * @return the player ID of this PokerTablePlayer
     */
    public long getPlayerId();

    /**
     * Sets the player ID of this PokerTablePlayer.
     *
     * @param playerId the player ID of this PokerTablePlayer
     */
    public void setPlayerId(long playerId);

    /**
     * Returns the time joined of this PokerTablePlayer.
     *
     * @return the time joined of this PokerTablePlayer
     */
    public Date getTimeJoined();

    /**
     * Sets the time joined of this PokerTablePlayer.
     *
     * @param timeJoined the time joined of this PokerTablePlayer
     */
    public void setTimeJoined(Date timeJoined);

    /**
     * Returns the time left of this PokerTablePlayer.
     *
     * @return the time left of this PokerTablePlayer
     */
    public Date getTimeLeft();

    /**
     * Sets the time left of this PokerTablePlayer.
     *
     * @param timeLeft the time left of this PokerTablePlayer
     */
    public void setTimeLeft(Date timeLeft);

    /**
     * Returns the amount won of this PokerTablePlayer.
     *
     * @return the amount won of this PokerTablePlayer
     */
    public double getAmountWon();

    /**
     * Sets the amount won of this PokerTablePlayer.
     *
     * @param amountWon the amount won of this PokerTablePlayer
     */
    public void setAmountWon(double amountWon);

    /**
     * Returns the created by of this PokerTablePlayer.
     *
     * @return the created by of this PokerTablePlayer
     */
    @AutoEscape
    public String getCreatedBy();

    /**
     * Sets the created by of this PokerTablePlayer.
     *
     * @param createdBy the created by of this PokerTablePlayer
     */
    public void setCreatedBy(String createdBy);

    /**
     * Returns the created date of this PokerTablePlayer.
     *
     * @return the created date of this PokerTablePlayer
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this PokerTablePlayer.
     *
     * @param createdDate the created date of this PokerTablePlayer
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the updated by of this PokerTablePlayer.
     *
     * @return the updated by of this PokerTablePlayer
     */
    @AutoEscape
    public String getUpdatedBy();

    /**
     * Sets the updated by of this PokerTablePlayer.
     *
     * @param updatedBy the updated by of this PokerTablePlayer
     */
    public void setUpdatedBy(String updatedBy);

    /**
     * Returns the updated date of this PokerTablePlayer.
     *
     * @return the updated date of this PokerTablePlayer
     */
    public Date getUpdatedDate();

    /**
     * Sets the updated date of this PokerTablePlayer.
     *
     * @param updatedDate the updated date of this PokerTablePlayer
     */
    public void setUpdatedDate(Date updatedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(PokerTablePlayer pokerTablePlayer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<PokerTablePlayer> toCacheModel();

    @Override
    public PokerTablePlayer toEscapedModel();

    @Override
    public PokerTablePlayer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
